In [24]:
import pandas as pd
import json
import time
import csv
import requests
import random

In [25]:
list3 = []
for line in open('compile.json', 'r'):
    list3.append(json.loads(line))
print(list3[:2])

[{'Headline': "IMAX film 'National Parks Adventure' celebrates parks", 'Summary': 'A new IMAX movie debuts Friday, starring geysers, red rock canyons, mountaintops and redwood forests. Called "National Parks Adventure," the film celebrates ...', 'Link': '/wires/ap/article-3442881/IMAX-film-National-Parks-Adventure-celebrates-parks.html', 'Query': 'parks', 'search_page_url': 'https://www.dailymail.co.uk/home/search.html?offset=0&size=50&sel=site&searchPhrase=parks&sort=relevant&type=article&days=all'}, {'Headline': 'PARKS ANNOUNCES RETIREMENT', 'Summary': 'Former Scotland fly-half Dan Parks has announced his retirement from rugby. Parks won 67 caps during an eight-year international career that ended when he st...', 'Link': '/wires/pa/article-2668993/PARKS-ANNOUNCES-RETIREMENT.html', 'Query': 'parks', 'search_page_url': 'https://www.dailymail.co.uk/home/search.html?offset=0&size=50&sel=site&searchPhrase=parks&sort=relevant&type=article&days=all'}]

In [26]:
type(list3)

list

In [27]:
df = pd.DataFrame(list3)
df

,Headline,Summary,Link,Query,search_page_url
0,IMAX film 'National Parks Adventure' celebrate...,"A new IMAX movie debuts Friday, starring geyse...",/wires/ap/article-3442881/IMAX-film-National-P...,parks,https://www.dailymail.co.uk/home/search.html?o...
1,PARKS ANNOUNCES RETIREMENT,Former Scotland fly-half Dan Parks has announc...,/wires/pa/article-2668993/PARKS-ANNOUNCES-RETI...,parks,https://www.dailymail.co.uk/home/search.html?o...
2,PARKS SECURE £34.5M LOTTERY CASH,Parks across the UK have been awarded £34.5 mi...,/wires/pa/article-2683442/PARKS-SECURE-34-5M-L...,parks,https://www.dailymail.co.uk/home/search.html?o...
3,'Reinstate Qld parks': conservationists,Conservationists want the Queensland governmen...,/wires/aap/article-3057005/Reinstate-Qld-parks...,parks,https://www.dailymail.co.uk/home/search.html?o...
4,Tim Parks: THE SERVER,‘Sit in silence and be still’ - that’s what yo...,/home/books/article-2142406/Tim-Parks-THE-SERV...,parks,https://www.dailymail.co.uk/home/search.html?o...
...,...,...,...,...,...
23065,Poll: People still seek meaty news on media bu...,WASHINGTON (AP) — A new study finds Americans ...,/wires/ap/article-2583210/Poll-People-seek-mea...,"arts, culture, entertainment and media",https://www.dailymail.co.uk/home/search.html?o...
23066,"On the media buffet, people still seek meaty news",WASHINGTON (AP) — Americans of all ages still ...,/wires/ap/article-2582915/On-media-buffet-peop...,"arts, culture, entertainment and media",https://www.dailymail.co.uk/home/search.html?o...
23067,Girl power: Latin American journalists take on...,"By Sophie HaresTEPIC, Mexico, Feb 13 (Thomson ...",/wires/reuters/article-5386715/Girl-power-Lati...,"arts, culture, entertainment and media",https://www.dailymail.co.uk/home/search.html?o...
23068,Journalist's home raided over spying story,Federal police have raided the home of a journ...,/wires/aap/article-7101615/Journalists-home-ra...,"arts, culture, entertainment and media",https://www.dailymail.co.uk/home/search.html?o...
23069,"In Weinstein's wake, is Hollywood truly capabl...","LOS ANGELES (AP) - ""That's how it works,"" actr...",/wires/ap/article-4985152/In-Weinsteins-wake-H...,"arts, culture, entertainment and media",https://www.dailymail.co.uk/home/search.html?o...

In [28]:
from fake_useragent import UserAgent
ua = UserAgent()
print(ua.random)

Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36

In [65]:
from newspaper import Article
title_comp = []
date_comp = []
authors_comp = []
text_comp = []
top_image_comp = []
movies_comp = []
query_comp = []
sp_url_comp = []
page_url_comp = []
from lxml.html import fromstring
def get_proxies():
    url = 'https://free-proxy-list.net/'
    response = requests.get(url)
    parser = fromstring(response.text)
    proxies = []
    for i in parser.xpath('//tbody/tr')[:100]:
        if i.xpath('.//td[7][contains(text(),"yes")]'):
            #Grabbing IP and corresponding PORT
            proxy = ":".join([i.xpath('.//td[1]/text()')[0], i.xpath('.//td[2]/text()')[0]])
            #print(proxy)
            proxies.append(proxy)
    return proxies
proxies = get_proxies()
#print(proxies)
user_agent_list = [
    'Mozilla/5.0 (X11; CrOS i686 4319.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36',
    'Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36',
    'Mozilla/5.0 (X11; CrOS i686 4319.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36'
    ]

for link,query,sp_url in zip(df['Link'],df['Query'],df['search_page_url']):
    url = "https://www.dailymail.co.uk" + link
    #Pick a random user agent
    user_agent = random.choice(user_agent_list)
    proxy = random.choice(proxies)
    #Set the headers 
    headers = {'User-Agent': user_agent}
    #Make the request
    #print(proxy, user_agent)
    try:
        r = requests.get(url, proxies={"http": proxy, "https": proxy}, headers = headers, timeout = 10)
    #r = requests.get(url, headers = headers, timeout = 60)
    except:
        r = ''
    #print(r.text)

    try:
        article = Article("")
        article.html = r.text
        article.download_state = 2
        article.parse()
        article.title
        article.publish_date
        article.authors
        article.text
        article.top_image
        article.movies
        title_comp.append(article.title)
        date_comp.append(article.publish_date)
        authors_comp.append(article.authors)
        text_comp.append(article.text)
        top_image_comp.append(article.top_image)
        movies_comp.append(article.movies)
    except :
        title_comp.append('')
        date_comp.append('')
        authors_comp.append('')
        text_comp.append('')
        top_image_comp.append('')
        movies_comp.append('')



    page_url_comp.append(url)
    query_comp.append(query)
    sp_url_comp.append(sp_url)
    time.sleep(4)

#print(query_comp)
# print(sp_url_comp)
# print(page_url_comp)
#print(title_comp)
# print(date_comp)
# print(authors_comp)
# print(text_comp)
# print(top_image_comp)
# print(movies_comp)

In [69]:
result14 = pd.DataFrame({
'query' : query_comp,
'search_result_page_url' : sp_url_comp,
'page_url' : page_url_comp,
'title' : title_comp,
'date' : date_comp,
'authors' : authors_comp,
'text' : text_comp,
'top_image' : top_image_comp,
'movies' : movies_comp
})
result_n = result_m.append(result14)
print(result_n.shape)

(22986, 9)

In [70]:
result_n.head()

,query,search_result_page_url,page_url,title,date,authors,text,top_image,movies
0,parks,https://www.dailymail.co.uk/home/search.html?o...,https://www.dailymail.co.uk/wires/ap/article-3...,,,,,,
1,parks,https://www.dailymail.co.uk/home/search.html?o...,https://www.dailymail.co.uk/wires/pa/article-2...,PARKS ANNOUNCES RETIREMENT,2014-06-25 11:03:15+01:00,[Press Association],PARKS ANNOUNCES RETIREMENT\n\nFormer Scotland ...,https://i.dailymail.co.uk/i/pix/m_logo_636x382...,[]
2,parks,https://www.dailymail.co.uk/home/search.html?o...,https://www.dailymail.co.uk/wires/pa/article-2...,,,,,,
3,parks,https://www.dailymail.co.uk/home/search.html?o...,https://www.dailymail.co.uk/wires/aap/article-...,'Reinstate Qld parks': conservationists,2015-04-27 06:47:04+01:00,"[Australian Associated, Australian Associated ...",'Reinstate Qld parks': conservationists\n\nCon...,https://i.dailymail.co.uk/i/pix/m_logo_636x382...,[]
4,parks,https://www.dailymail.co.uk/home/search.html?o...,https://www.dailymail.co.uk/home/books/article...,,,,,,

In [71]:
result_n.to_csv('final_parsed_data1.csv')